---
title: "AlgorithmComparisonSim"
output: html_document
---

```{r Libraries}

library(tidyverse)
library(scater)
library(splatter)
library(Seurat)
library(cluster)

```

```{r Functions}


# takes parameters specified and returns a number of seurat objects to those specifications, just in a list. they'll be slightly different since theres randomness and we make sure the random seed is different each time. 

make_a_dataset <- function(batchCells, group.prob, de.prob, nGenes, proj_name) {
  
  # batchCells - a vector giving the number of cells per batch, ie two batches with 100 cells is (100, 100)
  # group.prob - vector specifying probabilities per group, ie (0.5, 0.5) will likely give two same sized groups
  # de.prob - probability that genes will be DE by group(?) i.e. that they'll differ more than just noise
  # nGenes - number of genes to simulate
  # proj_name - character name of dataset or for the parameter object
  # all else we leave as default values. 
  
  # a bit of input validation
  stopifnot(
    is.numeric(batchCells),
    is.numeric(group.prob),
    is.numeric(de.prob),
    is.numeric(nGenes),
    is.character(proj_name)
  ) 
  
  # initialise and set params
  params <- newSplatParams()
  
  params <- setParams(params, update = list(
    batchCells = batchCells, 
    group.prob = group.prob, 
    de.prob = de.prob,
    nGenes = nGenes
    ))
  
  # simulate based on those parameters
  sim <- splatSimulate(params, method = "groups")
  
  counts_matrix <- counts(sim)
  seurat_obj <- CreateSeuratObject(counts = counts_matrix, project = proj_name)
  
  # then we want to add the true labelling in case we want to do arandi
  seurat_obj$true_labelling <- colData(sim)$Group
  
  return(seurat_obj)
  
}



```

```{r Real Data}



```

At present my biggest concern with the below data is that the SCTransform is hanging on to only the 100 most variable genes. I have not found this answer immediate from documentation so I need to dig a bit more for that, or maybe am missing something. 

```{r Simulated Data}

sim1 <- make_a_dataset(
  batchCells = 300,
  group.prob = c(0.25, 0.25, 0.25, 0.25),
  de.prob = 0.3, 
  nGenes = 2000,
  proj_name = "sim1"
)

sct_sim1 <- SCTransform(sim1) 




```

```{r More Functions}

# take SCTransformed seurat (i.e ready for dim red and clustering) and then run KMeans on its counts matrix with no dimensionality reduction

run_kmeans <- function(sct_seurat_object, k = NULL) {
  
  sct_scaled <- LayerData(
    object = sct_seurat_object, 
    assay = "SCT", 
    layer = "scale.data")

  if (is.numeric(k) == TRUE) {
    centers = k
  } else {
    clusGapcall <- clusGap(
      x = sct_scaled,
      FUNcluster = kmeans,
      K.max = 10,
      B = 5
    )
    
    centers <- maxSE(clusGapcall$Tab[, "gap"],
                     clusGapcall$Tab[, "SE.sim"],
                     method = "firstSEmax")
  }
  
  # run kmeans:
  kmobject <- kmeans(sct_scaled,
                     centers = centers,
                     nstart = 25)
  
  return(kmobject)
  
}

# Takes a seurat object post-SCTransform. Estimates a workable number of PCs, runs PCA, clusters on that number of PCs.

run_PCAkmeans <- function(sct_seurat_object, k = NULL) {
  
  # sct_seurat_object - object of class seurat with SCTransform applied
  # k - centers for KMeans. If left NULL, estimated with Gap Statistic
  
  PCA_sct_seurat_object <- RunPCA(sct_seurat_object, npcs = 100, verbose = TRUE)
  
  # pull PCA embeddings
  embeddings <- Embeddings(PCA_sct_seurat_object)
  
  # run kmeans

  if (is.numeric(k) == TRUE) {
    centers = k
  } else {
    clusGapcall <- clusGap(
      x = embeddings,
      FUNcluster = kmeans,
      K.max = 10,
      B = 5
    )
    
    centers <- maxSE(clusGapcall$Tab[, "gap"],
                     clusGapcall$Tab[, "SE.sim"],
                     method = "firstSEmax")
  }
  
  # run kmeans:
  kmobject <- kmeans(embeddings,
                     centers = centers,
                     nstart = 25)
  
  return(kmobject)
  
}

# Takes a seurat object post-SCTransform. Runs the Louvain Algorithm native to Seurat, IF we can make sure it's not doing any extra optimisation under the hood. Otherwise, we can pull the count data, make the SNN graph and cluster ourselves.

run_louvain <- function(sct_seurat_object, resolution  = NULL) {
  
  sct_seurat_object <- sct_seurat_object |> 
    RunPCA(npcs = 100) |> 
    FindNeighbors(dims = 1:30)
    
  
  
  lv_sct <- FindClusters(sct_seurat_object, algorithm = 1)
  
  return(lv_sct)
  
}

```

```{r Simulate}

kmeans_sct_sim1 <- run_kmeans(sct_sim1)

pca_kmeans_sct_sim1 <- run_PCAkmeans(sct_sim1)

lv_sct_sim1 <- run_louvain(sct_sim1)


# for the louvain clustering

p_sct_sim1 <- sct_sim1 |> 
    RunPCA(npcs = 100) |> 
    FindNeighbors(dims = 1:30)

embeddings <- Embeddings(p_sct_sim1, reduction = "pca")[, 1:30]

lv_clusters <- as.numeric(Idents(sct_sim1))
dist_mat <- dist(embeddings)
lv_sil <- silhouette(lv_clusters, dist_mat)
lv_avg_sil <- mean(lv_sil[, 3])

# then need to run louvain on this 


```

```{r Write}



```



