---
title: "KMeansCurseSim"
output: html_document
---



```{r Libraries}

library(tidyverse) # for general stuff
library(factoextra) # for clustering
library(cluster) # for clustering
library(mclust) # for more clustering specifically the arandi
library(data.table) # for faster writing to csv

```

```{r Functions}

# m - number of rows in total - must be divisible by K
# n - number of dimensions for the dataset (number of columns)
# N - noise dimensions to be added to the dataset 'in post' of the generation
# k - clusters to generate
# Overlap - boolean variable, whether the variances of each cluster should be inflated s.t. they overlap, or should they be well-separated?
simple_data <- function(m, n, N, k, overlap) {
  
  # make sure nothing's gonna break
  stopifnot(
    is.logical(overlap), 
    m %% k == 0
  )
  
  # check some options based on our arguments
  if (overlap == TRUE) {
    p_var <- rep(0.5, k) 
  } else {
    p_var <- rep(0.2, k)
  }
    
  
  # initialise entire result matrix
  rowtotal <- m
  coltotal <- n + N + 1
  
  result <- matrix(0, nrow = rowtotal, ncol = coltotal)
  
  # and initialise the noise that we'll add in
  if (N > 0) {
    all_the_noise <- matrix(rnorm(rowtotal * N, mean = 0, sd = 0.3), 
                            nrow = rowtotal,
                            ncol = N)
  }
  
  # create centre data as separate matrices in 'unmerged'
  for (i in 1:k) {
    cat("generating cluster ", i, "... \n")
    
    row_start <- (i - 1) * m / k + 1
    row_end <- i * m / k
    
    # add in the signal bit
    result[row_start:row_end, 1:n] <- rnorm(m / k * n, i, p_var[[i]])
    
    # add in the noise bit
    if (N > 0) {
      result[row_start:row_end, (n + 1):(n + N)] <- all_the_noise[row_start:row_end, ]
    }
    
    # add in the tag
    result[row_start:row_end, coltotal] <- i
    
    cat("finished cluster ", i, "... \n")
  }
  
  cat("finished all clusters... \n")
  
  # convert it to data frame
  frame <- as.data.frame(result)
  
  names(frame)[1:n] <- paste0("dim", 1:n)
  if (N != 0) {
    names(frame)[(n + 1):(n + N)] <- paste0("noise", 1:N)
  }
  
  names(frame)[ncol(frame)] <- "Tag"
  
  return(frame)
  
}

# uses simple_data to slice, cluster and score a passed dataset.
slice_cluster_score <- function(data, v, true_k = NULL) {
  # data - dataset to be sliced n scored
  # v - vector of dimension numbers to take arandi score at
  # true_k - true number of clusters. if left unpassed, gap statistic will be used to estimate
  
  #get true labels
  true_labels <- data$Tag
  
  #drop the tag col 
  data_no_tag <- select(data, -Tag)
  
  # initialise scores vector
  scores <- numeric(length(v))
  
  # slice the dataset, estimate k with gap statistic, then add the arandi to scores vector
  for (i in seq_along(v)) {
    
    # slice:
    current_slice <- data_no_tag[, 1:v[i], drop = FALSE] # changed to v[i]
    cat(i, "done slicing \n")
    
    # cluster:
    
    # estimate k:
    # clusGapcall <- clusGap(
    #   x = current_slice,
    #   FUNcluster = kmeans,
    #   K.max = 10,
    #   B = 5
    # )
    
    # k_estimated <- maxSE(clusGapcall$Tab[, "gap"],
    #                      clusGapcall$Tab[, "SE.sim"], 
    #                      method = "firstSEmax")
    
    # run kmeans:
    
    if (is.null(true_k)) {
      # if k is null, we estimate it here
      clusGapcall <- clusGap(
        x = current_slice,
        FUNcluster = kmeans,
        K.max = 10,
        B = 5 # maybe needs increased, this is comically low but for speed initially 5
      )
      
      use_k <- maxSE(clusGapcall$Tab[, "gap"],
                     clusGapcall$Tab[, "SE.sim"],
                     method = "firstSEmax")
      
    } else {
      use_k <- true_k
    }
    
    kmobject <- kmeans(current_slice, 
                       centers = use_k,
                       nstart = 25)
    
    #cat(i, "done clustering \n")
    
    scores[i] <- mclust::adjustedRandIndex(true_labels, kmobject$cluster)
    
    #cat("Dimension: ", v[i], "gives arandi score: ", round(scores[i], 4), " \n")
    
  }
  
  # format data frame for output
  result <- data.frame(
    dimension = v,
    score = scores
  )
  
  return(result)
  
}



```

```{r Creating Datasets}

# m consistent across all sets. cluster size varying. 3 at 3 clusters, 4 at 4, 3 at 5. 
# creating a dataframe with these parameters to store alongside as a (very) primitive attempt at a metadata file

metadata <- tibble(
  
  index = character(),
  name = character(),
  m = character(),
  n = character(),
  N = character(),
  k = character(),
  overlap = character()
  
)

generation_parameters <- list(
  
  list(1, "set1", 1200, 10, 10^5 - 10, 3, TRUE),
  list(2, "set2", 1200, 10, 10^5 - 10, 3, TRUE),
  list(3, "set3", 1200, 10, 10^5 - 10, 3, FALSE),
  list(4, "set4", 1200, 10, 10^5 - 10, 4, TRUE),
  list(5, "set5", 1200, 10, 10^5 - 10, 4, TRUE),
  list(6, "set6", 1200, 10, 10^5 - 10, 4, FALSE),
  list(7, "set7", 1200, 10, 10^5 - 10, 4, FALSE),
  list(8, "set8", 1200, 10, 10^5 - 10, 5, TRUE),
  list(9, "set9", 1200, 10, 10^5 - 10, 5, TRUE),
  list(10, "set10", 1200, 10, 10^5 - 10, 5, FALSE)
  
)


temp_set <- do.call(simple_data, generation_parameters[[1]][3:7])
metadata <- metadata |> add_row(index = generation_parameters[[1]][1], 
                    name = generation_parameters[[1]][2],
                    m = generation_parameters[[1]][3],
                    n = generation_parameters[[1]][4],
                    N = generation_parameters[[1]][5],
                    k = generation_parameters[[1]][6],
                    overlap = generation_parameters[[1]][7]
                    )

for (i in 1:length(generation_parameters)) {
  for (j in 1:ncol(metadata)) {
    
    metadata[i,j] <- generation_parameters[[i]][j]
  }
}

```

we are kinda seeing that it takes ~20s to make each data set. so let's keep a running estimate of how this works. but yeah now we want to write these out to the appropriate folder along with the metadata file. 

```{r Generation Loop Itself Estimating K}

log_sequence <- unique(round(10^seq(2, 4, length.out = 5)))

for (i in 1:10) {
  
  start_time <- Sys.time()
  
  temp_set <- do.call(simple_data, metadata[i, 3:7])
  cat("made some data, ", i, " \n")
  
  end_time <- Sys.time()
  runtime <- end_time - start_time
  
  cat("it took ", runtime, " \n")
  
  temp_score <- slice_cluster_score(temp_set, log_sequence)
  
  cat("done the score for set", i, ", writing it out now \n")
  
  fwrite(temp_score, file = paste0("C:/Users/fmhfl/Desktop/Undergrad Project/undergrad_project/DATA/KMeansCurseSimTestSet/", metadata[i, "name"][[1]], ".csv"))
  
  cat("written out the ", i, "th file \n")
  
}

```



```{r Making the Data for the Plot}

log_sequence <- unique(round(10^seq(2, 4, length.out = 5)))

test_data <- simple_data(m = 1200, n = 10, N = 10^4 - 10, k = 4, overlap = TRUE)

trial <- slice_cluster_score(data = test_data, v = log_sequence, true_k = 4)

```


```{r Plot, echo=TRUE}

plot1 <- ggplot(data = trial, mapping  = aes(dimension, score)) +
  geom_point() +
  geom_smooth() +
  scale_x_log10() +
  xlab("Dimension") +
  ylab("Adjusted Rand Index") +
  labs(title = "Adjusted Rand Index vs Dimension")

plot1

```

