---
title: "Visualise"
output: html_document
---

```{r Libraries}

library(tidyverse)
library(data.table)
library(viridis)

```

```{r vizcluster25}

# first aim of the game is to read in the set, and plot its first two PCs against each other to see what we got.
SET <- fread("D:/AlgorithmComparisonSim/BaseSim/set25")
TRUTH <- fread("D:/AlgorithmComparisonSim/BaseSim/set25true_labels")
PCAKMEANS <- fread("D:/AlgorithmComparisonSim/BaseSim/PK25")
LOUVAIN <- fread("D:/AlgorithmComparisonSim/BaseSim/LV25")
LEIDEN <- fread("D:/AlgorithmComparisonSim/BaseSim/LD25")

# we do a lil pre processing. first transpose it, which will mean our columns have low and zero variances. so we drop those that do. 
SET <- t(SET)
SET <- SET[, apply(SET, 2, var) != 0]

#now TRUTH has a weird format that we need to recover. 
TRUTH$true_group <- as.numeric(str_remove_all(TRUTH$true_group, "Group"))

#now Louvain has assignments 0-3 instead of 1-4
LOUVAIN$cluster <- LOUVAIN$cluster + 1


PCA <- prcomp(SET,
              center = TRUE,
              scale. = TRUE)
# PCA$rotation <- -1 * PCA$rotation
# PCA$x <- -1 * PCA$x

#plot(PCA$x[, 1], PCA$x[, 2])

plot_data <- tibble(
  X = PCA$x[, 1],
  Y = PCA$x[, 2],
  truth = TRUTH$true_group,
  pcakmeans = PCAKMEANS$cluster,
  louvain = LOUVAIN$cluster,
  leiden = LEIDEN$cluster
)

# Reshape data to long format for faceting
plot_data_long <- plot_data %>%
  pivot_longer(
    cols = c(truth, pcakmeans, louvain, leiden),
    names_to = "method",
    values_to = "cluster"
  ) %>%
  mutate(
    method = factor(method, 
                   levels = c("truth", "pcakmeans", "louvain", "leiden"),
                   labels = c("True Groups", "PCA K-means", "Louvain", "Leiden"))
  )

# Create faceted plot
vizcluster25 <- ggplot(data = plot_data_long) +
  geom_point(mapping = aes(x = X, y = Y, colour = factor(cluster)), alpha = 0.7) +
  facet_wrap(~ method, nrow = 2) +
  labs(
    title = "Clustering Results: Base Simulation Set 25",
    x = "PC1",
    y = "PC2",
    colour = "Cluster"
  ) +
  theme_minimal() +
  theme(legend.position = "right") +
  scale_color_viridis_d(option = "viridis")

if (!file.exists("C:/Users/fmhfl/Desktop/Undergrad Project/undergrad_project/OUTPUTS/vizcluster25.png")) {
  ggsave("C:/Users/fmhfl/Desktop/Undergrad Project/undergrad_project/OUTPUTS/vizcluster25.png",
         plot = vizcluster25,
         width = 7,
         height = 5,
         dpi = 600,
         units = "in")
} else {
  cat("vizcluster25 already exists \n")
}


```

```{r silzoomsep}

# on paper what do we want from these plots
# i think essentially we want to facet the silhouette one by colour, creating new boxplots for each. just to help us view and quote out point statistics while we talk about it. 

# so what do we need to load in? this isn't just one set we need. it's an allscores object, specifically the sep one. 

metadata_acsSEP <- fread("D:/AlgorithmComparisonSim/SeparationSim/metadata_acsSEP")

metadata_acsSEP <- metadata_acsSEP |> 
  mutate(
    ID = as.numeric(ID),
    proj_name = as.character(proj_name),
    batchCells = as.numeric(batchCells),
    de.prob = as.numeric(de.prob),
    nGenes = as.numeric(nGenes),
    group.prob = strsplit(group.prob, "\\|") |>
      lapply(as.numeric)
  )

SEPSCORES_pk <- fread("D:/AlgorithmComparisonSim/SeparationSim/PK_SEP_allscores")
SEPSCORES_lv <- fread("D:/AlgorithmComparisonSim/SeparationSim/LV_SEP_allscores")
SEPSCORES_ld <- fread("D:/AlgorithmComparisonSim/SeparationSim/LD_SEP_allscores")

SEPSCORES_pk$algo <- "pk"
SEPSCORES_pk$sep <- metadata_acsSEP$de.prob

SEPSCORES_lv$algo <- "lv"
SEPSCORES_lv$sep <- metadata_acsSEP$de.prob

SEPSCORES_ld$algo <- "ld"
SEPSCORES_ld$sep <- metadata_acsSEP$de.prob

SEPSCORES <- rbind(SEPSCORES_pk, SEPSCORES_lv, SEPSCORES_ld)

# but as of right now this has no sep info, which is the same vector that we want from the metadata

# Extract the 4 plasma colors for sep values 0.1, 0.2, 0.3, 0.4
plasma_colors <- viridis(4, option = "C")
names(plasma_colors) <- c("0.1", "0.2", "0.3", "0.4")

# Faceted plot with matching colors
silzoomsep <- ggplot(data = SEPSCORES, aes(x = algorithm, y = avg_silhouette)) +
  geom_point(aes(color = factor(sep)), 
             position = position_jitter(width = 0.2, height = 0), 
             alpha = 1, size = 2) +
  geom_boxplot(alpha = 0.3, outlier.shape = NA) +
  facet_wrap(~ sep, scales = "free_y", labeller = label_both) +
  scale_color_manual(values = plasma_colors, guide = "none") +
  labs(
    x = "Algorithm",
    y = "Average Silhouette Score"
  ) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

if (!file.exists("C:/Users/fmhfl/Desktop/Undergrad Project/undergrad_project/OUTPUTS/silzoomsep.png")) {
  ggsave("C:/Users/fmhfl/Desktop/Undergrad Project/undergrad_project/OUTPUTS/silzoomsep.png",
         plot = vizcluster25,
         width = 7,
         height = 5,
         dpi = 600,
         units = "in")
} else {
  cat("silzoomsep already exists \n")
}


# after lunch, we neaten up these plots and make one for pcn as well. then we do the elbow plot. 

```

```{r silzoompcn}

metadata_acsPCN <- fread("D:/AlgorithmComparisonSim/PCNSim/metadata_acsPCN")

metadata_acsPCN <- metadata_acsPCN |> 
  mutate(
    ID = as.numeric(ID),
    proj_name = as.character(proj_name),
    batchCells = as.numeric(batchCells),
    de.prob = as.numeric(de.prob),
    nGenes = as.numeric(nGenes),
    group.prob = strsplit(group.prob, "\\|") |>
      lapply(as.numeric)
  )

PCNSCORES_pk <- fread("D:/AlgorithmComparisonSim/PCNSim/PK_PCN_allscores")
PCNSCORES_lv <- fread("D:/AlgorithmComparisonSim/PCNSim/LV_PCN_allscores")
PCNSCORES_ld <- fread("D:/AlgorithmComparisonSim/PCNSim/LD_PCN_allscores")

PCNSCORES <- rbind(PCNSCORES_pk, PCNSCORES_lv, PCNSCORES_ld)
pcvector <- c(rep(c(rep(5, 20), rep(10, 20), rep(20, 20)), 3))
PCNSCORES$pcn <- pcvector

#need to find a way to get pcs onto this frame

# but as of right now this has no sep info, which is the same vector that we want from the metadata

# Extract the 4 plasma colors for sep values 0.1, 0.2, 0.3, 0.4
plasma_colors <- viridis(3, option = "B")
names(plasma_colors) <- c("5", "10", "20")

# Faceted plot with matching colors
silzoompcn <- ggplot(data = PCNSCORES, aes(x = algorithm, y = avg_silhouette)) +
  geom_point(aes(color = factor(pcn)), 
             position = position_jitter(width = 0.2, height = 0), 
             alpha = 1, size = 2) +
  geom_boxplot(alpha = 0.3, outlier.shape = NA) +
  facet_wrap(~ pcn, scales = "free_y", 
             labeller = as_labeller(c(
               "5" = "5 PCs",
               "10" = "10 PCs",
               "20" = "20 PCs"
             ))) +
  scale_color_manual(values = plasma_colors, guide = "none") +
  labs(
    x = "Algorithm",
    y = "Average Silhouette Score"
  ) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# if (!file.exists("C:/Users/fmhfl/Desktop/Undergrad Project/undergrad_project/OUTPUTS/silzoomsep.png")) {
#   ggsave("C:/Users/fmhfl/Desktop/Undergrad Project/undergrad_project/OUTPUTS/silzoomsep.png",
#          plot = vizcluster25,
#          width = 7,
#          height = 5,
#          dpi = 600,
#          units = "in")
# } else {
#   cat("silzoomsep already exists \n")
# }

```

```{r choosepcs}

```


